### ISSUE TITLE
Reverse donut

### ISSUE THREAD

**Issue by q1044019** [Nhogs/popoto#54] opened 2019-03-14 17:43 UTC
Is there a way to show the donut to the relationships that arrive at the node (not just those originating at the node)? That would make it easier to search.

**Comment by Popotojs** [comment] 2019-03-18 09:32
Duplicate of #36

**Comment by Popotojs** [comment] 2019-03-18 09:37
Does #36 answers your question?
Would you like additional elements to differentiate the direction of the relationships in donuts?

**Comment by q1044019** [comment] 2019-03-18 20:55
#36 was what I'm looking for. Thanks.

**Closed as completed** 2019-03-19 11:03 UTC
